import type { EvaluationDataset } from "../evaluation/dataset";
import type { GroundTruthStressRecord, StabilityStatus, StressReason } from "../evaluation/stressTest";
import type { ReviewItem } from "./types";

export type QueueReason = StressReason | "CONSENSUS_GT_CONFLICT" | "INPUT_SENSITIVE" | "DESCRIPTION_SENSITIVE";
export interface StressQueueItem extends ReviewItem { stressStatus:StabilityStatus; attributeTier:"A"|"B"|"C"; stabilityScore:number; predictionSpread:number; reasons:QueueReason[]; dangerousMissSeverity:"NONE"|"MODERATE"|"SEVERE"|"CRITICAL"; insufficientEvidence:boolean }
export interface StressPayload {dataset:{id:string;version:string};records:GroundTruthStressRecord[]}
export interface QueueFilter {status?:StabilityStatus; tier?:"A"|"B"|"C"; attribute?:string; reason?:QueueReason; showStable?:boolean}
const distance=(v:number,min:number,max:number)=>v<min?min-v:v>max?v-max:0;
const aliases=(reasons:StressReason[]):QueueReason[]=>[...reasons,...(reasons.includes("MODEL_CONSENSUS_AGAINST_GT")?["CONSENSUS_GT_CONFLICT" as const]:[]),...(reasons.includes("INPUT_VARIANCE")?["INPUT_SENSITIVE" as const]:[]),...(reasons.includes("DESCRIPTION_VARIANCE")?["DESCRIPTION_SENSITIVE" as const]:[])];
export function importStressQueue(payload:StressPayload,dataset:EvaluationDataset):StressQueueItem[]{if(payload.dataset.version!==dataset.version)throw new Error("Stress dataset version mismatch");const menus=new Map(dataset.store.menus.map(x=>[x.id,x]));return payload.records.map((r):StressQueueItem=>{const menu=menus.get(r.menuId);if(!menu)throw new Error(`Unknown stress menu: ${r.menuId}`);const dangerous=Math.max(0,...r.predictions.filter(p=>p.confidence>=.8).map(p=>distance(p.value,r.groundTruthRange.min,r.groundTruthRange.max)));const dangerousMissSeverity:StressQueueItem["dangerousMissSeverity"]=dangerous>=.5?"CRITICAL":dangerous>=.35?"SEVERE":dangerous>=.2?"MODERATE":"NONE";return {menuId:r.menuId,menuName:menu.name,description:menu.description??"",attributeId:r.attributeId,existingRange:r.groundTruthRange,conflictTypes:aliases(r.reasons),stressStatus:r.status,attributeTier:r.attributeTier,stabilityScore:r.stabilityScore,predictionSpread:r.consensus.spread,reasons:aliases(r.reasons),dangerousMissSeverity,insufficientEvidence:r.reasons.includes("INSUFFICIENT_EVIDENCE")};}).sort(comparePriority);}
export function filterStressQueue(items:StressQueueItem[],filter:QueueFilter={}):StressQueueItem[]{return items.filter(x=>(filter.showStable||x.stressStatus!=="STABLE")&&(!filter.status||x.stressStatus===filter.status)&&(!filter.tier||x.attributeTier===filter.tier)&&(!filter.attribute||x.attributeId===filter.attribute)&&(!filter.reason||x.reasons.includes(filter.reason))).sort(comparePriority);}
export function comparePriority(a:StressQueueItem,b:StressQueueItem){const status=(x:StressQueueItem)=>x.stressStatus==="UNRESOLVED"?0:x.stressStatus==="QUESTIONABLE"?1:2;const danger=(x:StressQueueItem)=>x.dangerousMissSeverity==="CRITICAL"?0:x.dangerousMissSeverity==="SEVERE"?1:x.dangerousMissSeverity==="MODERATE"?2:3;const tierConflict=(x:StressQueueItem)=>x.attributeTier==="A"&&x.reasons.includes("CONSENSUS_GT_CONFLICT")?0:1;const disagreement=(x:StressQueueItem)=>x.reasons.includes("MODEL_DISAGREEMENT")?0:1;return status(a)-status(b)||danger(a)-danger(b)||tierConflict(a)-tierConflict(b)||disagreement(a)-disagreement(b)||(a.attributeTier==="C"?0:1)-(b.attributeTier==="C"?0:1)||a.stabilityScore-b.stabilityScore;}
