import "./business.css";

const Problem=({n,children}:{n:string;children:string})=><article><span>{n}</span><p>{children}</p></article>;
const Shot=({src,alt}:{src:string;alt:string})=><img src={`/business/${src}`} alt={alt}/>;
export default function BusinessPage(){return <div className="biz">
  <header className="biz-nav"><a className="biz-brand" href="/">EasyOrder</a><nav aria-label="서비스 소개"><a href="#problem">문제</a><a href="#solution">솔루션</a><a href="#technology">기술</a><a href="#adoption">도입</a><a href="#demo">Demo</a></nav></header>
  <main>
    <section className="biz-hero"><div><p className="tag">FOR BUSINESS</p><h1>메뉴는 많아졌지만,<br/>고객이 메뉴를 고르는 일은<br/>더 어려워졌습니다.</h1><p className="lead">EasyOrder는 몇 가지 쉬운 질문으로 고객의 취향을 좁히고 매장 메뉴 안에서 적합한 선택지를 추천하는 접근성 중심 키오스크 시스템입니다.</p><p className="callout">기존 주문 시스템을 모두 바꾸는 것이 아니라,<br/>메뉴를 고르는 과정을 더 쉽게 만듭니다.</p><div className="actions"><a href="/kiosk?store=cafe">고객 화면 체험</a><a href="/owner/new?demo=1">점주 도입 과정 체험</a><a className="secondary" href="#solution">어떻게 작동하나요?</a></div></div><Shot src="kiosk-question.png" alt="EasyOrder가 하나의 쉬운 추천 질문을 보여주는 고객 키오스크"/></section>
    <section id="problem" className="section"><p className="tag">THE PROBLEM</p><h2>이런 고민이 있으신가요?</h2><div className="problems"><Problem n="01">메뉴가 많아 고객이 키오스크 앞에서 오래 고민합니다.</Problem><Problem n="02">고령층이나 디지털 기기에 익숙하지 않은 고객이 주문을 어려워합니다.</Problem><Problem n="03">신메뉴와 잘 알려지지 않은 메뉴가 메뉴판 안에서 묻힙니다.</Problem><Problem n="04">직원이 매번 고객의 취향을 듣고 추천하기 어렵습니다.</Problem><Problem n="05">매장마다 메뉴가 달라 추천 기능을 매번 별도로 개발하기 어렵습니다.</Problem></div></section>
    <section id="solution" className="section dark"><p className="tag">A BETTER WAY TO CHOOSE</p><h2>메뉴를 고객이 찾아가는 방식에서,<br/>고객에게 맞는 메뉴를 좁혀주는 방식으로.</h2><div className="compare"><article><h3>기존 키오스크</h3><p>전체 메뉴 노출 → 카테고리 탐색 → 메뉴 비교 → 고객이 직접 결정</p></article><article className="easy"><h3>EasyOrder</h3><p>쉬운 질문 → 취향 좁히기 → 추천 후보 → 메뉴 선택 → 주문</p></article></div></section>
    <section className="section two"><div><p className="tag">CUSTOMER EXPERIENCE</p><h2>고객은 메뉴 구조를 외울 필요가 없습니다.</h2><ol className="steps"><li>몇 가지 쉬운 질문</li><li>취향과 조건 반영</li><li>추천 메뉴 3~5개</li><li>옵션 선택 및 주문</li></ol></div><div className="shots"><Shot src="kiosk-question.png" alt="고객 취향을 묻는 동적 질문 화면"/><Shot src="kiosk-recommendation.png" alt="답변을 반영한 추천 메뉴 화면"/></div></section>
    <section className="section two"><div><p className="tag">ACCESSIBILITY</p><h2>큰 글씨만으로는 충분하지 않습니다.</h2><p>문제는 글씨 크기뿐 아니라 사용자가 복잡한 메뉴 구조를 직접 탐색해야 한다는 점입니다. EasyOrder는 실수하지 않는 사용자를 가정하지 않습니다.</p><ul><li>한 화면 한 질문과 큰 터치 영역</li><li>Large Text Mode</li><li>이전으로 · 잘 모르겠어요 · 처음으로</li><li>직원 도움과 결제 실패 복구</li></ul></div><aside className="soft"><small>SOFT SCORING</small><h3>한 번 잘못 눌러도<br/>다시 찾을 수 있습니다.</h3><p><s>답변과 맞지 않는 메뉴 즉시 제거</s></p><p>답변을 점수로 누적해 한두 번의 실수로 원하는 메뉴가 바로 사라지지 않게 합니다.</p></aside></section>
    <section className="section"><p className="tag">STORE-AGNOSTIC</p><h2>하나의 추천 엔진, 서로 다른 매장</h2><p className="intro">매장별 기준은 Schema로 정의하고 Question Generator, Scoring, Selector는 같은 엔진을 사용합니다. 현재 서로 다른 3개 도메인에서 동일 구조의 동작을 검증했습니다.</p><div className="domains"><article><h3>Cafe</h3><p>coffee · sweetness<br/>milk · refreshing</p></article><article><h3>Korean Snack</h3><p>spiciness · fried<br/>broth · chewy</p></article><article><h3>Fast Food</h3><p>fried · cheesy<br/>meaty · fresh</p></article></div></section>
    <section className="section two owner"><div><p className="tag">OWNER ONBOARDING</p><h2>개발자에게 메뉴 등록을 요청할 필요가 없습니다.</h2><ol className="steps"><li>매장 정보</li><li>메뉴 직접 입력 / CSV / JSON</li><li>추천 기준 선택</li><li>메뉴 자동 분석</li><li>애매한 항목만 확인</li><li>키오스크 미리보기</li><li>완료</li></ol><a className="inline-cta" href="/owner/new?demo=1">점주용 매장 만들기 체험</a></div><Shot src="owner-wizard.png" alt="점주가 매장 정보를 입력하고 메뉴를 등록하는 위저드"/></section>
    <section id="technology" className="section dark ai"><p className="tag">RESPONSIBLE AI</p><h2>AI가 고객의 메뉴를<br/>마음대로 결정하지 않습니다.</h2><div className="pipeline"><span>점주 메뉴</span><b>↓</b><span>AI 메뉴 분석 보조</span><b>↓</b><span>신뢰도와 점주 확인</span><b>↓</b><span>확정 Store Data</span><b>↓</b><span>재현 가능한 추천 엔진</span><b>↓</b><span>고객 추천</span></div><div className="cards"><article><h3>AI</h3><p>메뉴 이름·설명 해석<br/>초기 추천 속성 생성<br/>점주의 입력 부담 감소</p></article><article><h3>Recommendation Engine</h3><p>사용자 답변 누적<br/>후보 점수와 동적 질문 계산<br/>최종 추천 후보 생성</p></article></div><p className="callout">AI는 데이터를 준비하는 일을 돕고,<br/>고객 추천은 재현 가능한 엔진이 담당합니다.</p></section>
    <section className="section two"><div><p className="tag">HUMAN-IN-THE-LOOP</p><h2>AI가 확실하지 않다면 사람이 확인합니다.</h2><p>AI가 확신하지 못하는 값만 점주에게 보여주고, 점주가 직접 확인한 값은 이후 자동 분석이 덮어쓰지 않습니다.</p><Shot src="owner-review.png" alt="AI가 확실하지 않은 메뉴 속성을 점주가 확인하는 화면"/></div><div><p className="tag">RELIABILITY &amp; SAFETY</p><h2>추천 시스템은 실패를 전제로 설계했습니다.</h2><dl className="reliability"><dt>AI 분석 실패</dt><dd>Fallback과 점주 검토</dd><dt>사용자 오답</dt><dd>Soft Scoring</dd><dt>중복 터치</dt><dd>상태 전이 방어</dd><dt>결제 실패</dt><dd>Cart 유지와 재시도</dd><dt>잘못된 CSV</dt><dd>정상 행 보존과 오류 행 수정</dd><dt>중간 이탈</dt><dd>LocalStorage Resume</dd></dl></div></section>
    <section className="section evidence"><p className="tag">TECHNICAL VALIDATION</p><h2>아이디어에서 끝내지 않고 검증했습니다.</h2><div className="evidence-grid"><span>3-domain architecture</span><span>Playwright Local E2E 8/8</span><span>Vercel Remote Smoke 2/2</span><span>Test · Typecheck · Build</span><span>Bundle Secret Audit</span><span>Evaluation · Stress Test · Audit</span></div><p className="research"><strong>RESEARCH RESULT</strong> Snack automated stress-test의 provisionally stable subset에서 Luna 98.77%, Terra 100%를 기록했습니다. 이는 human-verified Ground Truth가 아니며 연구용 지표입니다.</p></section>
    <section className="section"><p className="tag">CONCEPT COMPARISON</p><h2>기존 방식과 무엇이 다른가요?</h2><div className="table-wrap"><table><thead><tr><th>구분</th><th>일반 키오스크</th><th>단순 AI 추천</th><th>EasyOrder</th></tr></thead><tbody><tr><th>메뉴 탐색</th><td>직접 탐색</td><td>AI 결과 중심</td><td>질문 기반 탐색</td></tr><tr><th>오답 복구</th><td>제한적</td><td>모델에 따라 다름</td><td>Soft Scoring + 이전</td></tr><tr><th>AI 의존</th><td>없음</td><td>높음</td><td>데이터 준비에 제한</td></tr><tr><th>점주 검토</th><td>없음</td><td>보통 없음</td><td>Human-in-the-loop</td></tr><tr><th>업종 확장</th><td>매장 시스템 의존</td><td>데이터·모델 의존</td><td>Store Schema</td></tr><tr><th>주문 흐름</th><td>지원</td><td>별도 필요 가능</td><td>Checkout Demo 연결</td></tr></tbody></table></div></section>
    <section className="section"><p className="tag">EXPECTED BENEFITS</p><h2>EasyOrder가 검증하려는 효과</h2><div className="domains"><article><h3>고객</h3><p>탐색 부담과 선택 단계 단순화, 디지털 취약 고객의 접근성 개선 가능성</p></article><article><h3>점주</h3><p>설명·추천 부담 감소, 다양한 메뉴 노출, 추천 데이터 구축 감소 가능성</p></article><article><h3>운영사</h3><p>업종별 엔진 재개발 부담 감소와 Kiosk/POS 앞단 추천 Layer 가능성</p></article></div><p className="research">현재 제품 가설이며 실제 매장 A/B Test를 통한 정량 검증이 향후 과제입니다.</p></section>
    <section id="adoption" className="section two"><div><p className="tag">TARGET INTEGRATION ARCHITECTURE</p><h2>기존 주문 시스템을 모두 교체하지 않는 방향을 목표로 합니다.</h2><div className="integration"><strong>EasyOrder</strong><span>질문 → 추천 → 메뉴 선택</span><b>↓</b><strong>Existing Kiosk / POS</strong><span>옵션 → 장바구니 → 결제</span></div><p className="future">FUTURE TARGET · 실제 POS 연동은 아직 구현되지 않았습니다.</p></div><div><p className="tag">ADOPTION FLOW</p><h2>매장 적용은 이렇게 진행할 수 있습니다.</h2><h3>현재 Prototype</h3><p>메뉴 데이터 → 추천 기준 → 자동 분석 → 점주 확인 → Preview → Store JSON</p><h3>향후 상용화</h3><p>POS/Kiosk Adapter → 현장 QA → 운영</p><h3>적합한 대상</h3><p>메뉴가 많은 카페 · 선택지가 다양한 매장 · 접근성을 고민하는 점주 · Kiosk/POS 업체 · 프랜차이즈 운영사</p></div></section>
    <section id="demo" className="final"><p className="tag">SEE IT IN ACTION</p><h2>직접 확인해 보세요.</h2><p>고객에게는 더 쉬운 선택을,<br/>점주에게는 관리 가능한 추천 시스템을.</p><div className="actions"><a href="/kiosk?store=cafe">고객 키오스크 체험</a><a href="/owner/new?demo=1">점주 도입 과정 체험</a><a className="secondary" href="/">Demo Home</a></div></section>
  </main><footer className="biz-footer"><strong>Portfolio Prototype</strong><p>공개 Demo는 Mock AI와 LocalStorage를 사용하며 실제 PG/POS 및 상용 운영 인프라를 포함하지 않습니다.</p></footer>
</div>}
